services:
  omnisave:
    image: omnisave-server:latest
    container_name: omnisave
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /volume1/omnisave/config:/config
      - /volume1/omnisave/data:/data
